### ISSUE TITLE
IVCT web UI: use empty path to access UI

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#131]
To access the IVCT web UI I need to use a URL like ``http://<host>:8180/nato.ivct.gui.nato.ivct.gui.ui.html``. An empty path should be sufficient: ``http://<host>:8180``.

**Comment by rhzg** [comment]
I'm currently testing to configure the server.xml with

<Context path="" docBase="ivct.gui.ui.html"> </Context>

that requires to modifiy the docker image. It seems to work and I will release it as soon as possible

**Comment by PHameete** [comment]
Hi Reinhard,

you can find the Tomcat config that is pushed to the GUI docker image in the docker directory of the GUI component. Let me know if you need an help with that.

**Comment by bergtwvd** [comment]
As far as I can see this works now in the latest build. There is no need for a long URL pathname anymore. I'll close the issue.
