### ISSUE TITLE
Runner should output the TS version used

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#155]
It would be good to see some information in the log about the TS version that is used by the Runner,
Just a sanity check to make sure the correct version is used. Maybe as simple as the content of a VERSION file that is echo-ed on the output.

**Comment by rhzg** [comment]
The runner (TestEngine, TC.exec) now shows the release tag together with 'git describe --all' information about the actual code version. This function is included in the Factory. initialize and will be shown in all IVCT  processes as logger.info message.  see #200
