### ISSUE TITLE
CI: Publish to Maven Central

### ISSUE THREAD

**Issue by rhzg** [IVCTool/IVCT_Framework#161]
The IVCT framework components shall be made available as compiled and signed artifacts within maven central. This is required to build test suites independently from the framework.

**Comment by rhzg** [comment]
I created a project on sonatype (responsible for providing access to maven central) with the group id: io.github.msg134.

The account is bound to my email (reinhard.herzog@iosb.fraunhofer.de)

**Comment by PHameete** [comment]
Nice. WIll you handle configuration of the deploy in the gradle script?

I believe that for deploying via Travis we will need an extra account that is also allowed to deploy to that group on maven central. Unless you want to use your own account for this.

**Comment by rhzg** [comment]
I'm working on that gradle script (within branch https://github.com/MSG134/IVCT_Framework/tree/maven-central ) 
We have the required POM files, the signatures but we are struggling with the :TC.lib:uploadArchives task.

**Comment by rhzg** [comment]
as well as: 
https://oss.sonatype.org/content/repositories/snapshots/io/github/msg134/Command/1.0.2-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/io/github/msg134/MessagingHelpers/1.0.2-SNAPSHOT/

**Comment by ducana** [comment]
To use the sonatype repository, need the following changes to the gradle files in the test suite 

1) for each .shared/commons.gradle file
repositories:
     repositories {
                .
                .
               maven {
                       url 'https://oss.sonatype.org/content/repositories/snapshots'
               }
     }

2) for each .shared/libraries.gradle file  using e.g. the version 1.0.2-SNAPSHOT
change the ivctVersion
     ivctVersion = '1.0.2-SNAPSHOT'
add the following library definition
     tc_lib:                                   "io.github.msg134:TC-lib:1.0.2-SNAPSHOT"

3) for each test suite specific gradle file e.g. TS_HLA_EncodingRulesTester/TS_HLA_EncodingRulesTester.gradle

dependencies {
change
       compileOnly     group: 'msg134-ivct-framework', name: 'IEEE1516e', version: ivctVersion
       compileOnly     group: 'msg134-ivct-framework', name: 'TC.lib', version: ivctVersion
       compileOnly     group: 'msg134-ivct-framework', name: 'MessagingHelpers', version: ivctVersion
to
       compileOnly     group: 'io.github.msg134', name: 'IEEE1516e', version: ivctVersion
       compileOnly     libraries.tc_lib
       compileOnly     group: 'io.github.msg134', name: 'MessagingHelpers', version: ivctVersion

       .
       .
      .
}

These changes will allow a test suite to be compiled without needing the IVCT_Framework.

**Comment by rhzg** [comment]
to do: the build need to be integrated into the IVCT_Framework/travis script

**Comment by rhzg** [comment]
integration into travis showed some incompatibility between the maven publishing plugin and the travis build environment. The POM naming task clashed with the gradle module naming convention. This requires more insight and testing, which will be rescheduled for release 3.0

**Comment by PHameete** [comment]
Hey @rhzg I've heard that Travis is having some problems with Java builds so this could be related?

**Comment by rhzg** [comment]
hi, yes maybe. The issue is with creating, signing and publishing a lib to maven

**Comment by PHameete** [comment]
Ok I think the issues were general build issues. So problably not then :-)

**Comment by rhzg** [comment]
with the current MAVEN/sonatype a full automation is not possible. Therefore this issue will closed.
