### ISSUE TITLE
Status information on running components

### ISSUE THREAD

**Issue by rhzg** [IVCTool/IVCT_Framework#196]
to use the IVCT system, certain components are required. Currently there is no status information available, that could be used within UI to indicate the overall status. It is also not possible to get information about actual configurations of the background processes, like the TC.exec or the LogSink. 

An enchancement would be "heartbeat" JMS message to be send regularly by the background processes with the actual status including the active environment settings, and to be shown within the UI. In the command line interface this could be shown in a "getStatus" command, and in the GUI this could be shown as a status flag (like "running" or "failure") which cklickable to show the detailed status.

**Comment by rhzg** [comment]
see also #197

**Comment by ducana** [comment]
The heartbeat logic has been implemented: the logSink and TC.exec processes send out the heartbeat message on a regular basis. These processes can include text in this message about their internal status or in case of process failure, the lack of heartbeat messages will be detected by the GUI or CL.
