### ISSUE TITLE
Heartbeat for IVCT background components

### ISSUE THREAD

**Issue by rhzg** [IVCTool/IVCT_Framework#197]
in the current GUI does not see the status of background processes like TC.exec and LogSink. Some kind of a heatbeat protocol should be implemented to report the status of non-user-interface processes via JMS messages.

**Comment by rhzg** [comment]
same as #143

**Comment by rhzg** [comment]
this features has been implemented and is in included in the development branch

**Comment by bergtwvd** [comment]
I just wonder if using the Active MQ management console achieves the same thing?

**Comment by rhzg** [comment]
No, it would not, because under normal circumstances the tcRunner or the LogSink would not send anything to ActiveMQ. So you would not know if these background processes are running and in good health.
