### ISSUE TITLE
Stacktrace when running the Portico compostion

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#211]
With the Portico composition I get the stacktrace below when I start a test case such as for hw_iosb, HLA-Declaration-2017, IR-SOM-00003.

````
tc-runner_1               | Exception in thread "Thread-4" java.lang.ExceptionInInitializerError
tc-runner_1               |     at nato.ivct.etc.fr.tc_hla_services.TC_001_Services_Check.logTestPurpose(TC_001_Services_Check.java:74)
tc-runner_1               |     at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:127)
tc-runner_1               |     at de.fraunhofer.iosb.testrunner.TestEngine$TestScheduleRunner.run(TestEngine.java:203)
tc-runner_1               |     at java.lang.Thread.run(Thread.java:745)
tc-runner_1               | Caused by: java.util.MissingResourceException: Can't find bundle for base name lang, locale en_US
tc-runner_1               |     at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
tc-runner_1               |     at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
tc-runner_1               |     at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
tc-runner_1               |     at nato.ivct.etc.fr.fctt_common.utils.TextInternationalization.<clinit>(TextInternationalization.java:13)
tc-runner_1               |     ... 4 more
````

**Comment by ducana** [comment]
I checked the exception and found out that the call to the method TextInternationalization.getString("etc_fra.purpose") is failing. This implies that the files lang_en_US.properties and lang_fr_FR.properties are not being found. These files have to made available to the application somehow: I don't have the answer to this problem. Does anyone have an idea?

**Comment by bergtwvd** [comment]
After some google research I found out the following:

- The Docker Alpine Linux images (used by the IVCT runner) do not contain locale files; these need to be installed separate (see e.g. https://github.com/gliderlabs/docker-alpine/issues/144)
- A method to add them is shown here: https://github.com/sgerrand/alpine-pkg-glibc

Dockerfile additions are:
````
RUN apk update
RUN apk --no-cache add ca-certificates wget
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-2.29-r0.apk
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-bin-2.29-r0.apk
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.29-r0/glibc-i18n-2.29-r0.apk

RUN apk add glibc-2.29-r0.apk
RUN apk add glibc-bin-2.29-r0.apk
RUN apk add glibc-i18n-2.29-r0.apk

RUN /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
RUN /usr/glibc-compat/bin/localedef -i fr_FR -f UTF-8 fr_FR.UTF-8

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8
````
I propose to add these steps to the the IVCT Runner Dockerfile.

If this fails, we need to change to another (but larger footprint) LRC base image such as Ubuntu.

**Comment by bergtwvd** [comment]
Although I believe the above is the solution, I wonder why this popped up just now. Are the (Pitch/MaK/Portico) container images ever used to run tests. Checking that these work has to be part of every release.

**Comment by bergtwvd** [comment]
I tested the above Dockerfile steps out and added them to the Portico base image Dockerfile for now. Also has to change to the OpenJDK as a sideline.

On the end got still the same error for the runner on test case IR-SOM-0003:

````
tc-runner_1               | Exception in thread "Thread-2" java.lang.ExceptionInInitializerError
tc-runner_1               |     at nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check.logTestPurpose(TC_001_Publish_Subscribe_Check.java:74)
tc-runner_1               |     at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:127)
tc-runner_1               |     at de.fraunhofer.iosb.testrunner.TestEngine$TestScheduleRunner.run(TestEngine.java:203)
tc-runner_1               |     at java.lang.Thread.run(Thread.java:748)
tc-runner_1               | Caused by: java.util.MissingResourceException: Can't find bundle for base name lang, locale en_US
tc-runner_1               |     at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1581)
tc-runner_1               |     at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
tc-runner_1               |     at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
tc-runner_1               |     at nato.ivct.etc.fr.fctt_common.utils.TextInternationalization.<clinit>(TextInternationalization.java:13)
tc-runner_1               |     ... 4 more
````

There is something else going on (too).

Maybe https://stackoverflow.com/questions/12986234/cant-find-bundle-for-base-name-bundle-locale-en-us/13942527

**Comment by rhzg** [comment]
I've seen this problem before, when the HLA BASE test cases are not able to find their language files. The error is cause by the module 

    nato.ivct.etc.fr.fctt_common.utils.TextInternationalization
which is used as common library for the basic HLA test cases. I missing files shall be in the jar file

    ETC_FRA_Common-2.0.0.jar:
    lang_en_US.properties
    lang_fr_FR.properties
which is included on the test suites HLA-Verification, HLA-Object, HLA-Declaration and HLA-Service. 

However, in my configurations the are present. Also I do not see this exception when executing the test cases with the pRTI in my environment. Which compose file are you using?

**Comment by bergtwvd** [comment]
I use the docker compose files from the Composition repository.

As far as I can determine the Pitch files include the resource bundle files (where in the JARs I cannot determine). When I use a docker image without the Pitch JAR files, I get exactly the same problem as wit the other RTI versions.

So the issue is missing resource bundle files in the IVCT installation.

Just instantiate the following class to reproduce the error:

````
package nl.tno.locale;

import java.util.Locale;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

public class TextInternationalization 
{
//	private static final String mBundleName = "nato.ivct.etc.fr.resources.lang";
	private static final String mBundleName = "lang";
	//private static final Locale locale = new Locale(System.getProperty("user.language"), System.getProperty("user.country"));
	private static final Locale locale = new Locale("en", "US");

	
	private static ResourceBundle mResourceBundle = ResourceBundle.getBundle(mBundleName,locale);
	
	/**
	 * Get the value of the key passed in parameter
	 * @param key String represents the key of the text wanted
	 * @return The text as String
	 */
	public static String getString(String key) 
	{
		try 
		{
			return mResourceBundle.getString(key);
		} 
		catch (MissingResourceException e) 
		{
			return '!' + key + '!';
		}
	}
}
````

**Comment by bergtwvd** [comment]
Reran the test where I included the file `lang_en_US.properties` in the resources directory of the Java test application. Now the test application works since it can find the file. This means that the issue is with the IVCT configuration.  With the Pitch RTI there is a `lang_en.properties` and `lang.properties` file in the root of the prticore.jar file. Java will pick up the first if it cannot find  `lang_en_US.properties`.

**Comment by rhzg** [comment]
What I do not understand is, why the lang properties are not found in you setup. I just checked the '/IVCT_Compositions/HelloWorld/docker-compose.yml' setup. Inside the tc-runner container I checked the content of the HLA-Declaration-2017 testsuite:

````
~/conf/TestSuites/TS_HLA_Declaration-2.0.0/lib # unzip -l ETC_FRA_Common-2.0.0.jar | grep lang
    17228  07-25-19 14:29   lang_en_US.properties
    18897  07-25-19 14:29   lang_fr_FR.properties
````
the lang propertie files are at the root level inside the ETC_FRA_Common-2.0.0.jar package, which is loaded by the classloader just before starting the testcase. The loading of the resource is done during runtime (not at startup time) based on the start test case command and should be independent from the rti version. It is even independent from the CLASSPATH which is used at startup time. 

I can not think of any reason, why these resouces are not included in the portico or mak distribution. Sorry, but I'm lost at this point.

**Comment by rhzg** [comment]
I just tested the ivct-portico/docker-compose.yml, and I have seen that indeed, inside the ETC_FRA_Common-2.0.0.jar there are no lang property files! That confuses me even more - I will have a closer look what doing on here.

**Comment by rhzg** [comment]
I've found the problem: the .gitignore file in the TS_HLA_BASE project tricked my into missing to 'git add' the language property files. Now they should be included in the docker images (2.0.0, master-latest and development-latest). 

(please make sure, your images are reloaded from the docker repo - I had to remove my copy manually before reload was done)

**Comment by bergtwvd** [comment]
The issue with Portico appears to be fixed, but now I cannot run the same test with either the Pitch or Mak RTI. I see the following error on the console when the Runner starts up:

````
tc-runner_1               | 2019-07-29 10:33:59,078 : IVCT_BADGE_HOME_ID folder not found
````

This causes the execution of test cases to fail later on.

**Comment by ducana** [comment]
The message here is not very good: the folder name should be given out as part of the error message. The problem is that the IVCT_BADGE_HOME_ID value being used is either a non existing folder or it is not a directory.

**Comment by bergtwvd** [comment]
I do not see the error in the latest build. So close.
