### ISSUE TITLE
Test execution does not start when selecting RPR-encoding test IP-EN-00002

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#212]
I run the following compositions:
- ivct_pitch (https://github.com/IVCTool/IVCT_Compositions/tree/master/ivct-pitch)
- sut-shipsim-pitch (https://github.com/IVCTool/IVCT_Compositions/tree/master/sut-shipsim-pitch)

Once the IVCT is up I login and navigate to SUT vrf > RPR-Encoding-2.0  and select test case IP-EN-00002.

However nothing happens.  Also the console does not show anything.

**Comment by ducana** [comment]
When using the command line interface, there is no problem with running RPR-Encoding-2.0. One suggestion is to check if the settingsDesignator value is correct. If the settingsDesignator value is wrong, the symptoms appear to match those described in this issue. There have been changes to the setting of common parameters of an SUT lately: the correct usage depends on the IVCT version - where there are some subtile changes between versions.

**Comment by bergtwvd** [comment]
The more important it is to include the execution of the docker compose files in the build and test process! :-). I believe the issue is a missing settings file, but Reinhard can confirm this.

**Comment by rhzg** [comment]
I can now replicate this issue and I can confirm that the 

    /root/conf/IVCTsut/vrf/RPR-Encoding-2.0/TcParam.json

is missing. But there must be something else wrong in this composition, because I'm not able to create a new SuT. I will sync with John to have a closer look into this.

**Comment by rhzg** [comment]
the original problem was, that the TestSuite folders have been empty. I fixed the problem by adding the test suite volumes to the gui service (like the it is done for the tc-runner).

However, I my HelloWorld compositions this has never been necessary, so I'm a bit confused here. So I'm not sure if this is the appropriate solution!?! Maybe I should have fixed the problem with some docker prune commands?

After adding the test suites, I was able to add and adjust the TC.params and also the extra files (BasicSimpleTypes.xml and RPR_FOM_2.0_1516-2010.xml from github/IVCT_Framework/RunTime/IVCTSut/vrf). With that, the test case worked:

````
Verdict Summary:
CORRECT: 256 INCORRECT: 0
[TRACE]: resignFederationExecution resignAction=DELETE_OBJECTS_THEN_DIVEST
[TRACE]: destroyFederationExecution federationExecutionName=TheWorld
[TRACE]: getParameterName return RequestStatus
[TRACE]: getParameterName whichClass=Interaction class<127>, theHandle=parameter<378>
[WARN]: terminateRti: FederatesCurrentlyJoined (ignored)
[INFO]: TC INCONCLUSIVE Have not seen all required attributes and parameters

**Comment by bergtwvd** [comment]
Ok, the TS datavolumes need to be mounted at both the GUI and the Runner containers. I'll update the docker compositions and close this issue.
