### ISSUE TITLE
Allow for empty setting designator

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#216]
The IVCT GUI enforces a non-empty RTI settings designator. This way it is impossible that the system ever falls back on the default. In the case of the IVCT Docker version the default can be set from the docker-compose file. Setting the default from the compose file is quite useful for automation (less action required from the user). Request therefore to allow for an empty string.

**Comment by bergtwvd** [comment]
This enhancement is needed urgently to assist testing the IVCT with different RTIs.

**Comment by rhzg** [comment]
possible solution is to use empty string in CS.json, and interpret this as a fallback to the default value

**Comment by rhzg** [comment]
other option is to include a boolean property in the CS.json, like "USE_DEFAULT_SETTINGS_DESIGNATOR" to overwrite the actual CS setting.

**Comment by bergtwvd** [comment]
Tried editing the CS file, but no effect.

These is a SETTINGS_DESIGNATOR ENV, but the handling is entirely unclear, see https://github.com/IVCTool/IVCT_Framework/issues/229.

**Comment by rhzg** [comment]
handling should work as desribed in https://github.com/IVCTool/IVCT_Framework/blob/development/docs/src/2-8-IVCT_Configuration.adoc 

Currently using default settings instead of using the CS settings is not possible. This requires GUI extension --> feature request

**Comment by bergtwvd** [comment]
Given the handling as described on https://github.com/IVCTool/IVCT_Framework/blob/development/docs/src/2-8-IVCT_Configuration.adoc, I propose to set the value of the `SETTINGS_DESIGNATOR` to an empty string.  The currently listed default value is Pitch RTI specific.

The LRC Base image currently uses `FEDERATIONNAME` (see https://ci.tno.nl/gitlab/msaas/general/lrc). The naming needs to be aligned (TBD).

**Comment by rhzg** [comment]
agreed. I have changed the default SETTINGS_DESIGNATOR to an empty string, in order to avoid vendor specfic IVCTool defaults.
