### ISSUE TITLE
New SUT configured via UI does not work

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#221]
When I create a new SUT `MySUT` for the `RPR-Encoding-2.0`, then the `TcParam.json` file under the SUT folder uses the Hello World settings:

````
~/conf/IVCTsut/MySUT/RPR-Encoding-2.0 # more TcParam.json
{
  "federationName" : "HelloWorld",
  "rtiHostName"     : "localhost",
  "rtiPort"         : "8989",
  "sutFederateName" : "A",
  "sleepTestTimeWaitSeconds" : "60",
  "fomFiles"        : [
    { "fileName"    : "$(IVCT_SUT_HOME_ID)/hw_iosb/TS_HLA_EncodingRulesTester-2017/HelloWorld.xml" },
    { "fileName"    : "$(IVCT_SUT_HOME_ID)/hw_iosb/TS_HLA_EncodingRulesTester-2017/BasicSimpleTypes.xml" }
  ],
  "somFiles"        : [
    { "fileName"    : "$(IVCT_SUT_HOME_ID)/hw_iosb/TS_HLA_EncodingRulesTester-2017/BasicSimpleTypes.xml" },
    { "fileName"    : "$(IVCT_SUT_HOME_ID)/hw_iosb/TS_HLA_EncodingRulesTester-2017/HelloWorld.xml" }
  ]
}
````
I do not see a way to get the SOM/FOM file in here, unless I manually copy it in and adapt the TcParam.json file.

I need to copy in `BasicSimpleTypes.xml` and `RPR_FOM_v2.0_1516-2010.xml` to `/root/conf/IVCTsut/MySUT/RPR-Encoding-2.0` and adapt `TcParam.json` to the following in order to execute the encoding test:

````
~/conf/IVCTsut/MySUT/RPR-Encoding-2.0 # more TcParam.json
{
  "federationName" : "TheWorld",
  "rtiHostName" : "crc",
  "rtiPort" : "8989",
  "sutFederateName" : "VRF/UG",
  "sleepTestTimeWaitSeconds" : "60",
  "fomFiles"        : [
    { "fileName"    : "$(IVCT_SUT_HOME_ID)/MySUT/RPR-Encoding-2.0/RPR_FOM_v2.0_1516-2010.xml" },
    { "fileName"    : "$(IVCT_SUT_HOME_ID)/MySUT/RPR-Encoding-2.0/BasicSimpleTypes.xml" }
  ],
  "somFiles"        : [
    { "fileName"    : "$(IVCT_SUT_HOME_ID)/MySUT/RPR-Encoding-2.0/RPR_FOM_v2.0_1516-2010.xml" },
    { "fileName"    : "$(IVCT_SUT_HOME_ID)/MySUT/RPR-Encoding-2.0/BasicSimpleTypes.xml" }
  ]
}
````

The UI must provide a way to upload the SOM/FOM for a SUT.

**Comment by rhzg** [comment]
Uploading these files is possible within the SuT tab, in the extra parameter section. There is a upload file button, to add additional files.

**Comment by ducana** [comment]
The "new SUT" logic has been modified to include any files found in the testsuite source repository src/main/resources/ExtraParamTemplates folder. These will be added to the testsuite jar files when gradlew install is invoked. In the runtime environment, the "new SUT" function will be copy any files found in the testsuite jar ExtraParamTemplates folder into the sut testsuite folder with values that may need modification. NB. This has only been inplemented in the TestSuites branch at this time.

**Comment by ducana** [comment]
The TestSuites branch has been merged into development, thus the logic described above is available for any new SUTs created.
