### ISSUE TITLE
TC runner error message in console output

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#223]
I notice the following message in the console output of the TC runner. The message is marked as an  error. The volumes actually already exist from a previous run, although I see the same error when starting with a clean sheet. Serious error?

````
tc-runner_1               | Starting the Dockerized IVCT Test Case Engine
tc-runner_1               | 20:53:10.058 [main] INFO  nato.ivct.commander.Factory - IVCT Version 2.1.0-SNAPSHOT, build v2.0.1-64-g688fc96
tc-runner_1               | 20:53:10.075 [main] DEBUG nato.ivct.commander.Factory - /root/application exists
tc-runner_1               | 20:53:10.076 [main] DEBUG nato.ivct.commander.Factory - /root/application is directory
tc-runner_1               | 20:53:10.076 [main] ERROR nato.ivct.commander.Factory - Environment Variable IVCT_CONF = IVCT_CONF not found - creating default values
tc-runner_1               | 20:53:10.086 [main] WARN  nato.ivct.commander.Factory - New IVCT.properties file has been created with default values. Please verify settings!
tc-runner_1               | 20:53:10.088 [main] WARN  nato.ivct.commander.Factory - {}
tc-runner_1               | 20:53:10.088 [main] DEBUG nato.ivct.commander.Factory - Properties used: {}
tc-runner_1               | 20:53:10.304 [main] DEBUG d.f.i.m.PropertyBasedClientSetup - initConnection: connect to activemq please wait...
...
````

**Comment by bergtwvd** [comment]
When I define the ENV `IVCT_CONF` in the composition (setting it to `/root/conf`) the error message disappears. I now get what I expect:

````
tc-runner_1               | Starting the Dockerized IVCT Test Case Engine
tc-runner_1               | 21:22:41.645 [main] INFO  nato.ivct.commander.Factory - IVCT Version 2.1.0-SNAPSHOT, build v2.0.1-64-g688fc96
tc-runner_1               | 21:22:41.665 [main] DEBUG nato.ivct.commander.Factory - /root/conf exists
tc-runner_1               | 21:22:41.666 [main] DEBUG nato.ivct.commander.Factory - /root/conf is directory
tc-runner_1               | 21:22:41.666 [main] DEBUG nato.ivct.commander.Factory - Properties file loaded
tc-runner_1               | 21:22:41.666 [main] DEBUG nato.ivct.commander.Factory - Properties used: {SETTINGS_DESIGNATOR=crcAddress=localhost:8989, ivctcommander.queue=commands}
````

Later on I still see the message:
````
tc-runner_1               | 2019-08-05 21:22:42,965 : IVCT_BADGE_HOME_ID folder not found
````

Unclear how harmful this is.

So, seems that the IVCT_CONF default is not correctly handled.

**Comment by rhzg** [comment]
Two issues here. First, the version indicates that this is not the latest build with the updated default handling. Second, the Factory trace shows that the IVCT_CONF environment variable was set to "/root/application". That is show by the lines:

~~~~
| 20:53:10.075 [main] DEBUG nato.ivct.commander.Factory - /root/application exists
tc-runner_1               | 20:53:10.076 [main] DEBUG nato.ivct.commander.Factory - /root/application is directory
~~~~

The following error message was wrong, as it did not show the actual value but just the key name for the value:

~~~~
tc-runner_1               | 20:53:10.076 [main] ERROR nato.ivct.commander.Factory - Environment Variable IVCT_CONF = IVCT_CONF not found - creating default values
~~~~

that code has been corrected in the latest release

**Comment by bergtwvd** [comment]
I see the same error using the Portico composition, see https://github.com/IVCTool/IVCT_Framework/issues/226.

Had to work-around the issue using the ENV IVCT_CONF.

**Comment by rhzg** [comment]
I found the problem. The environment variable IVCT_CONF is set in all 3 dockerfiles for ma,pi and po 

~~~~
ENV IVCT_CONF /root/application
~~~~

So, removing the setting from the compose file only caused that it was not overwritten. I believe the best solution is to remove the setting from the compose file. I'll see if that causes any side effects.

**Comment by bergtwvd** [comment]
Looking at the code, it is safe to delete the line `ENV IVCT_CONF /root/application` from the Dockerfiles (pi, ma, po).

**Comment by rhzg** [comment]
issue solved
