### ISSUE TITLE
Unclear ENV handling by IVCT applications

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#229]
In the file IVCT_Framework/Command/src/main/java/nato/ivct/commander/Factory.java ENV VARS are processed, including SETTINGS_DESIGNATOR.

When I set the ENV SETTINGS_DESIGNATOR for the TC Runner container I see from the log output that the value is indeed picked up in the Factory code. In this example I use as value an empty string `""`.

However, in the GUI the default is still displayed (`crcAddress=...`). Does the TC Runner still use the ENV value?  The GUI application does not seem to processe the ENVs.

When a test is executed, the value from the GUI appears to be passed on to the TC Runner.

So, it is entirely unclear for what IVCT application each ENV can be used, and if an ENV setting has any effect at all.

**Comment by rhzg** [comment]
Also the logic for the SuT federate name is unclear. It used be defined within the TcParam.json, but has now moved to CS.json. The GUI handling is unclear as it used the non-editable SuT ID field as the federate name.

**Comment by rhzg** [comment]
the latest snapshot release has a new feature to add sutFederateName into the conformance statement and edit this value along with the federationName in the SuT settings. GUI and CL are supporting this feature.

**Comment by rhzg** [comment]
ENV handling is not documented in https://github.com/IVCTool/IVCT_Framework/blob/development/docs/src/2-8-IVCT_Configuration.adoc
