### ISSUE TITLE
Support for multi-TC.exec deployments

### ISSUE THREAD

**Issue by rhzg** [IVCTool/IVCT_Framework#235]
A TC.exec (tc-runner) needs to be linked to a specific RTI. In order to run test cases against SuT within different RTIs, the IVCTool deployment needs at least one TC.exec for each RTI. That requires to add a RTI type information to the SuT conformance statement, along with the settings designator. 

The run test case command needs to be extended with the RTI-specific address, in order to be send to the correct RTI-specific TC.exec instance

**Comment by fschoeppenthau** [comment]
The IVCT system allows the use of several TestEngines.
A selection menu in the IVCT settings allows the selection of an active TestEngine.

Further Information: https://github.com/IVCTool/IVCT_Operation/blob/develop/docs/src/IVCT-GettingStarted-Graphical-User-Interface.adoc#testengine-settings

Version 4.0 includes the TestEngine extensions.
