### ISSUE TITLE
IVCT Documentation: rename TS_HelloWorld repo

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#237]
As discussed before, proposal is to rename this to `IVCT_TestCases` for the Test Case Developer.

**Comment by bergtwvd** [comment]
And move Test Case/Suite related pages from the Framework repo to this repo.

**Comment by rhzg** [comment]
Proposal is: IVCT_TestSuiteDevelopment

**Comment by rhzg** [comment]
repository has been renamed to https://github.com/IVCTool/IVCT_TestSuiteDevelopment
