### ISSUE TITLE
IVCT: SuT Capability Status

### ISSUE THREAD

**Issue by michaeltheis** [IVCTool/IVCT_Framework#239]
Define how the conformance status of a SuT and each of its capability badges is defined.

**Comment by rhzg** [comment]
Options are:

1. PASSED if all test cases are passed at least once
2. PASSED if last execution of all test cases is passed
3. PASSED if all test cases executions are passed
4. PASSED if "certification mode" is active and all test cases are executed once with verdict passed.

others ideas?

**Comment by fschoeppenthau** [comment]
Currently number 2 is applied: PASSED if last execution of all test cases is passed.

**Comment by fschoeppenthau** [comment]
More information about the SuT Capability Status / Conformance Status: https://github.com/IVCTool/IVCT_Operation/blob/develop/docs/src/IVCT-GettingStarted-Graphical-User-Interface.adoc#sut-capability-status--conformance-status

**Comment by rhzg** [comment]
solved
