### ISSUE TITLE
Runner: default value for SETTINGS_DESIGNATOR must be an empty string

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#242]
Currently the default for this EV is `crcAddress=localhost:8989` (see `https://github.com/IVCTool/IVCT_Framework/blob/development/docs/src/2-8-IVCT_Configuration.adoc`). This must be an empty string.

**Comment by ducana** [comment]
The IVCT testsystem now has an empty default value for SETTINGS_DESIGNATOR. The documentation has been updated as well.
NB. There are several possible locations where this value may be set: system variables, IVCT.properties file, CS.json file or in a user created bat/shell file starting the program. Thus it may be necessary to check all of these if SETTINGS_DESIGNATOR has to be set to an empty string.
NB. The Pitch RTI uses the "CRC Address" value from the configured "pRTI LRC Settings Editor" for SETTINGS_DESIGNATOR if this value is an empty string.
