### ISSUE TITLE
Conformance Report Generation

### ISSUE THREAD

**Issue by rhzg** [IVCTool/IVCT_Framework#244]
The results of an conformance test need to be documented. A formatted document shall be created.

see also #185

**Comment by fschoeppenthau** [comment]
A report function has been developed that allows a detailed PDF report to be generated on the result of the conformance test. More information about the test report:
https://github.com/IVCTool/IVCT_Operation/blob/develop/docs/src/IVCT-GettingStarted-Graphical-User-Interface.adoc#create-test-report

**Comment by rhzg** [comment]
is implemented
