### ISSUE TITLE
Change usage of testsuite and testschedule naming in program code

### ISSUE THREAD

**Issue by ducana** [IVCTool/IVCT_Framework#261]
The first idea was to use testsuite and testschedule as concepts for lists of testcases: this is still visible in parts of the IVCT. These terms should be changed carefully to use badge instead. The main user of these terms is the UI project.

By using Eclipse refactoring this can be done fairly easily, but there is a slight danger of collapsing method names to something already existing.
Example: the class CmdListTestSuites should be changed to CmdListTestBadges to avoid the conflict with CmdListBadges which already exists!

**Comment by rhzg** [comment]
With the introduction of the concept of "Testsuite", this should be solved.
