### ISSUE TITLE
TC Params: add description field in file

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#294]
For each param, add a description field. The text in this field can be shown in the UI.

**Comment by rhzg** [comment]
that sounds like a good idea. I propose to add a list of parameter descriptions into the test suite definition file and to use that list ((name, description)) to extend the table within the SuT/testSuite.

the test case paremter file itself should not be changed, as this would cause the test case implementations to adopt to a new json structure.

**Comment by fschoeppenthau** [comment]
Successfully implemented: Read parameter descriptions from the test suite files (JSON) and display the parameter descriptions in the TS parameters table (UI).
