### ISSUE TITLE
End testcase command

### ISSUE THREAD

**Issue by ducana** [IVCTool/IVCT_Framework#84]
The test operator may at some point want to end a testcase gracefully (as opposed to an abort testcase). This feature would mean that the test case would finish running, with a verdict based on the observations evaluated up to this point in time, with the additional comment that the testcase was stopped by the test operator.

**Comment by rhzg** [comment]
a proposal would be to add a overwritteable method within the AbstractTestCase class that accepts a "EndTestCase" command. The command would be send by user

**Comment by rhzg** [comment]
see also #21

**Comment by rmauget** [comment]
By performing a certification in France with ETC FRA, I fully agree with that proposal. When the SuT is a man-in-the-loop simulator, it is very difficult (impossible?) to determine what is the right duration for an ETC to run before the System under Test produces the excepted results.
So, I think having an end testcase command will be a great help in that case.

**Comment by rhzg** [comment]
Combine end test case commands into one single JMS message, Options may be End, Kill, Abort

**Comment by fschoeppenthau** [comment]
A functionality to abort test cases was implemented in the IVCT version 3.1.0-SNAPSHOT.

- With the button <Abort> in the menu frame, a test case can be aborted.
- A test case is aborted with an INCONCLUSIVE verdict.
- The abort button is only displayed when a test case is running.

More information about the graphical user interface and the abort button:
https://github.com/IVCTool/IVCT_Operation/blob/develop/docs/src/IVCT-GettingStarted-Graphical-User-Interface.adoc#the-system-under-test-sut-view

Implementation:
- test case abort button - SuTTcExecutionForm.java
- onAbortTestCase function to abort the test case (thread) - TestEngine.java
- Assignment of thread to test case via the test case ID - TestEngine.java
- Thread pool introducted to limit the number of threads (MAX_THREADS = 10) - TestEngine.java
